In [1]:
from google.colab import drive
drive.mount('/content/drive', force_remount=True)
data_path = "drive/My Drive/_data/"
!ls "drive/My Drive/"
!ls "drive/My Drive/_data"




import sys
sys.path.append('drive/My Drive/')

import pandas as pd

import unicodedata
import re

import nltk
nltk.download('treebank')
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')
from nltk.corpus import stopwords
from nltk.stem import LancasterStemmer, WordNetLemmatizer
from nltk.corpus import stopwords
from nltk import word_tokenize


import os
import numpy as np
from keras.models import Sequential, Model
from keras.layers import *#Embedding,Bidirectional,Dense,Conv1D,Flatten,LSTM,GlobalMaxPooling1D,Dropout
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
from sklearn.manifold import TSNE
import matplotlib.pyplot as plt
import pickle

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive
classifier.py  FeatureSelection.py	Text0.ipynb  Text4.ipynb
_config.yml    New_Copy_of_Text6.ipynb	Text1.ipynb  Text5.ipynb
_data	       prediction.py		Text2.ipynb  Text6.ipynb
DataPrep.py    __pycache__		Text3.ipynb  Text7.ipynb
clustering_result.npy	  LSTM_Model4.h5      test.npy	     train.tsv
en_wiki_word2vec_300.zip  LSTM_Model6.h5      test.tsv	     valid.csv
glove.6B.100d.txt	  LSTM_Model6_new.h5  train.csv      valid_new.npy
glove.6B.50d.txt	  test.csv

In [7]:
data_file = data_path + "valid.csv"
df_v = pd.read_csv(data_file)
df_v = df_v.dropna() 

data_file = data_path + "test.csv"
df_t = pd.read_csv(data_file)
df_t = df_t.dropna()

data_file = data_path + "train.csv"
df = pd.read_csv(data_file)
df = df.dropna()

print(len(df))
print(len(df.columns))
print(df.columns)
df.head()


10240
2
Index(['Statement', 'Label'], dtype='object')


Statement  Label
0  Says the Annies List political group supports ...  False
1  When did the decline of coal start? It started...   True
2  Hillary Clinton agrees with John McCain "by vo...   True
3  Health care reform legislation is likely to ma...  False
4  The economic turnaround started at the end of ...   True

#preprocess

In [10]:
def remove_non_ascii(words):
    """Remove non-ASCII characters from list of tokenized words"""
    new_words = []
    for word in words:
        new_word = unicodedata.normalize('NFKD', word).encode('ascii', 'ignore').decode('utf-8', 'ignore')
        new_words.append(new_word)
    return new_words

def to_lowercase(words):
    """Convert all characters to lowercase from list of tokenized words"""
    new_words = []
    for word in words:
        new_word = word.lower()
        new_words.append(new_word)
    return new_words

def remove_punctuation_number(words):
    """Remove punctuation & number from list of tokenized words"""
    new_words = []
    for word in words:
        new_word = re.sub(r'([^\s\w]|_|[0-9])+', '', word)
        if new_word != '':
            new_words.append(new_word)
    return new_words

def remove_stopwords(words):
    """Remove stop words from list of tokenized words"""
    new_words = []
    for word in words:
        if word not in stopwords.words('english'):
            new_words.append(word)
    return new_words

stop_words = set(stopwords.words("english"))
def stem_words(words):
    """Stem words in list of tokenized words"""
    stemmer = LancasterStemmer()
    stems = []
    for word in words:
        stem = stemmer.stem(word)
        stems.append(stem)
    return stems

def lemmatize_verbs(words):
    """Lemmatize verbs in list of tokenized words"""
    lemmatizer = WordNetLemmatizer()
    lemmas = []
    for word in words:
        lemma = lemmatizer.lemmatize(word, pos='v')
        lemmas.append(lemma)
    return lemmas

def normalize(words):
    words = remove_non_ascii(words)
    words = to_lowercase(words)
    words = remove_punctuation_number(words)
    words = remove_stopwords(words)
    words = stem_words(words)
    words = lemmatize_verbs(words)
    return words

def norm_all_sent(_sentences):
  for _i,_w in enumerate(_sentences):
    # print(_i,_w)
    tmp_sentences = _w#_sentences[_w]
    tmp_sentences = word_tokenize(tmp_sentences)
    tmp_sentences = normalize(tmp_sentences)
    tmp_sentences = " ".join(tmp_sentences)
    _sentences[_i] = tmp_sentences
  return _sentences

In [9]:
embed_num_dims = 100
max_seq_len = 50

sentences = df['Statement'].values
sentences = norm_all_sent(sentences)
Y = df['Label'].values

sentences_t = df_t['Statement'].values
sentences_t = norm_all_sent(sentences_t)
Y_t = df_t['Label'].values

sentences_v = df_v['Statement'].values
sentences_v = norm_all_sent(sentences_v)
Y_v = df_v['Label'].values
Y_v = np.where(Y_v=='TRUE',True,False)

tokenizer = Tokenizer(num_words = 4000)
tokenizer.fit_on_texts(sentences)
sequence = tokenizer.texts_to_sequences(sentences)
sequence_t = tokenizer.texts_to_sequences(sentences_t)
sequence_v = tokenizer.texts_to_sequences(sentences_v)

index_of_words = tokenizer.word_index
print("len(index_of_words)",len(index_of_words))

padded_seq = pad_sequences(sequence , maxlen = max_seq_len )
padded_seq_t = pad_sequences(sequence_t , maxlen = max_seq_len )
padded_seq_v = pad_sequences(sequence_v , maxlen = max_seq_len )

from keras.utils import to_categorical
Y = to_categorical(Y)
Y_t = to_categorical(Y_t)
Y_v = to_categorical(Y_v)

X_train=padded_seq
Y_train=Y
X_test=padded_seq_t
Y_test=Y_t
X_val=padded_seq_v
Y_val=Y_v



len(index_of_words) 12327


#CredRank Algorithm
##Measuring User Credibility in Social Media

In [ ]:
# try:
#     import flair
# except:
#     !pip install flair
# import pickle
# from flair.embeddings import TransformerDocumentEmbeddings
# from flair.data import Sentence
# from IPython.display import clear_output


# selected_transformer_model="bert-base-cased"
# embedding = TransformerDocumentEmbeddings(selected_transformer_model)

# def sentence_embedding(input_S):
#     _input = Sentence(input_S)
#     embedding.embed(_input)
#     _input.get_embedding()
#     _emb = _input.get_embedding()
#     _emb = _emb.detach().numpy()
#     return _emb

# #########Train##############
# all_emb = []
# for _i,_sen in enumerate(df['Statement']):
#     x = _sen
#     _emb = sentence_embedding(x)
#     print(_i,'=>',_emb.shape)
#     all_emb.append(_emb)


# outfile = data_path + "train.npy"
# all_emb = np.array(all_emb)
# np.save(outfile, all_emb)
# clear_output()

# #########Test##############
# all_emb = []
# for _i,_sen in enumerate(df_t['Statement']):
#     x = _sen
#     _emb = sentence_embedding(x)
#     print(_i,'=>',_emb.shape)
#     all_emb.append(_emb)


# outfile = data_path + "test.npy"
# all_emb = np.array(all_emb)
# np.save(outfile, all_emb)

# #########Valid##############
# all_emb = []
# for _i,_sen in enumerate(df_v['Statement']):
#     x = _sen
#     _emb = sentence_embedding(x)
#     print(_i,'=>',_emb.shape)
#     all_emb.append(_emb)


# outfile = data_path + "valid.npy"
# all_emb = np.array(all_emb)
# np.save(outfile, all_emb)

# clear_output()


In [ ]:
data_file = data_path + "train.npy"
all_emb = np.load(data_file)
print("all_emb_train.shape=>",all_emb.shape)

data_file = data_path + "test.npy"
all_emb_t = np.load(data_file)
print("all_emb_test.shape=>",all_emb_t.shape)

data_file = data_path + "valid.npy"
all_emb_v = np.load(data_file)
print("all_emb_valid.shape=>",all_emb_v.shape)


tmp_all_emb = np.concatenate((all_emb,all_emb_t,all_emb_v))
print("tmp_all_emb.shape=>",tmp_all_emb.shape)

all_emb_train.shape=> (10240, 768)
all_emb_test.shape=> (2551, 768)
all_emb_valid.shape=> (2569, 768)
tmp_all_emb.shape=> (15360, 768)


In [ ]:
# # # # from scipy.cluster.hierarchy import dendrogram, linkage
# # # # from matplotlib import pyplot as plt

# # # # linked = linkage(all_emb_t[:10,:], 'single')

# # # # plt.figure(figsize=(10, 7))
# # # # dendrogram (linked,
# # # #             orientation='top',
# # # #             distance_sort='descending',
# # # #             show_leaf_counts=True)
# # # # plt.show()


from sklearn.cluster import AgglomerativeClustering
cluster = AgglomerativeClustering(n_clusters=2,affinity='euclidean', linkage='ward')# affinity="cosine", linkage='average')
tmp_c=cluster.fit_predict(tmp_all_emb)

outfile = data_path + "clustering_result.npy"
np.save(outfile, tmp_c)

In [ ]:
from collections import Counter

data_file = data_path + "clustering_result.npy"
tmp_c = np.load(data_file)


train_c = tmp_c[:len(all_emb)]
print(len(train_c))
print(np.unique(train_c))
print(Counter(train_c))
# print(Counter(Y_train.argmax(axis=1)))

test_c = tmp_c[len(all_emb):len(all_emb)+len(all_emb_t)]
print(len(test_c))
print(np.unique(test_c))
print(Counter(test_c))
# print(Counter(Y_train.argmax(axis=1)))

valid_c = tmp_c[len(all_emb)+len(all_emb_t):]
print(len(valid_c))
print(np.unique(valid_c))
print(Counter(valid_c))


n_of_m = Counter(train_c)
cluster_weight = np.zeros(len(n_of_m))
_tmp = np.array(list(n_of_m.values()))
_for_div = np.sum(np.sqrt(_tmp))
for _cluster in n_of_m:
    _c_i = np.sqrt(n_of_m[_cluster])
    # member_weight = np.sqrt(n_of_m[_cluster])/n_of_m[_cluster]
    cluster_weight[_cluster] = (_c_i/_for_div)#*member_weight


10240
[0 1]
Counter({0: 7974, 1: 2266})
2551
[0 1]
Counter({0: 2000, 1: 551})
2569
[0 1]
Counter({0: 2013, 1: 556})


#Word Embedding

In [ ]:
# !wget http://nlp.stanford.edu/data/glove.6B.zip
# !unzip glove*.zip
# !mv glove*.100d.txt 'drive/My Drive/_MrAnsari/_data'

f = open(data_path+'glove.6B.100d.txt')
embedd_index = {}
for line in f:
    val = line.split()
    word = val[0]
    coff = np.asarray(val[1:],dtype = 'float')
    embedd_index[word] = coff

f.close()
print('Found %s word vectors.' % len(embedd_index))

# a_file = open(data_path+"data.pkl", "wb")
# pickle.dump(embedd_index, a_file)
# a_file.close()

Found 400000 word vectors.


In [ ]:
# a_file = open(data_path+"data.pkl", "rb")
# output = pickle.load(a_file)
# print('Found %s word vectors.' % len(embedd_index))

embedd_index['good']

In [ ]:
embedding_matrix = np.zeros((len(index_of_words) + 1, embed_num_dims))

tokens = []
labels = []

for word,i in index_of_words.items():
    temp = embedd_index.get(word)
    if temp is not None:
        embedding_matrix[i] = temp
        
#for plotting
        tokens.append(embedding_matrix[i])
        labels.append(word)

print(embedding_matrix.shape)

(7059, 100)


In [ ]:
#TSNE algorithm used to visualize word embeddings having huge amount (100) dimensions

def tsne():
    
    tsne_model = TSNE(perplexity=40, n_components=2, init='pca', n_iter=2500, random_state=23)
    new_values = tsne_model.fit_transform(tokens[:200])
    print(new_values.shape)
    
    x = []
    y = []
    for value in new_values:
        x.append(value[0])
        y.append(value[1])
        
    plt.figure(figsize=(16,16)) 
    for i in range(len(x)):
        plt.scatter(x[i],y[i])
        plt.annotate(labels[i],
                     xy=(x[i], y[i]),
                     xytext=(5, 2),
                     textcoords='offset points',
                     ha='right',
                     va='bottom')
    plt.show()

    
    
    
    
tsne()

In [ ]:
from keras.optimizers import Adam

input1 = Input(shape=(max_seq_len,))
input2 = Input(shape=(1,))

#Embedding layer before the actaul BLSTM 
embedd_layer = Embedding(len(index_of_words) + 1 , embed_num_dims , input_length = max_seq_len , weights = [embedding_matrix])(input1)
BiLSTM = Bidirectional(LSTM(64 , return_sequences = True , dropout = 0.2 , recurrent_dropout = 0.2))(embedd_layer)
GMP = GlobalMaxPooling1D()(BiLSTM)
FC1 = Dense(32,activation = 'relu')(GMP)
FC1_d = Dropout(0.2)(FC1)
FC2 = Dense(2,activation = 'sigmoid')(FC1_d)
_newinput = Concatenate()([FC2, input2])
FC3 = Dense(2,activation = 'sigmoid')(_newinput)
model = Model(inputs=[input1, input2], outputs=FC3)
model.summary()

_adam = Adam(lr = 0.01)
model.compile(loss = 'categorical_crossentropy' , optimizer = 'rmsprop' , metrics = ['accuracy'])


Model: "functional_1"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_1 (InputLayer)            [(None, 50)]         0                                            
__________________________________________________________________________________________________
embedding (Embedding)           (None, 50, 100)      705900      input_1[0][0]                    
__________________________________________________________________________________________________
bidirectional (Bidirectional)   (None, 50, 128)      84480       embedding[0][0]                  
__________________________________________________________________________________________________
global_max_pooling1d (GlobalMax (None, 128)          0           bidirectional[0][0]              
_______________________________________________________________________________________

In [ ]:
new_data = []
for _i in range(len(train_c)):
    tmp_data = cluster_weight[train_c[_i]]
    new_data.append(tmp_data)
new_data = np.array(new_data)

new_data_t = []
for _i in range(len(test_c)):
    tmp_data = cluster_weight[test_c[_i]]
    new_data_t.append(tmp_data)
new_data_t = np.array(new_data_t)

new_data_v = []
for _i in range(len(valid_c)):
    tmp_data = cluster_weight[valid_c[_i]]
    new_data_v.append(tmp_data)
new_data_v = np.array(new_data_v)



In [ ]:
hist = model.fit([X_train,new_data],Y_train,epochs = 10 , batch_size = 256, validation_data = ([X_val,new_data_v],Y_val))

result = model.evaluate([X_test,new_data_t],Y_test)
print(result[1]*100)


model_file = data_path + "LSTM_Model.h5"
model.save(model_file)

Epoch 1/10
40/40 [==============================] - 9s 230ms/step - loss: 0.6856 - accuracy: 0.5617 - val_loss: 0.6926 - val_accuracy: 0.5200
Epoch 2/10
40/40 [==============================] - 8s 211ms/step - loss: 0.6768 - accuracy: 0.5617 - val_loss: 0.6860 - val_accuracy: 0.5200
Epoch 3/10
40/40 [==============================] - 8s 210ms/step - loss: 0.6728 - accuracy: 0.5617 - val_loss: 0.6860 - val_accuracy: 0.5200
Epoch 4/10
40/40 [==============================] - 8s 212ms/step - loss: 0.6695 - accuracy: 0.5617 - val_loss: 0.6844 - val_accuracy: 0.5200
Epoch 5/10
40/40 [==============================] - 8s 211ms/step - loss: 0.6665 - accuracy: 0.5636 - val_loss: 0.6795 - val_accuracy: 0.5356
Epoch 6/10
40/40 [==============================] - 8s 207ms/step - loss: 0.6619 - accuracy: 0.5738 - val_loss: 0.6800 - val_accuracy: 0.5333
Epoch 7/10
40/40 [==============================] - 8s 210ms/step - loss: 0.6569 - accuracy: 0.5757 - val_loss: 0.6753 - val_accuracy: 0.5403
Epoch 

In [ ]:
model_file = data_path + "LSTM_Model.h5"
model.load_weights(model_file)

result = model.evaluate([X_test,new_data_t],Y_test)
print(result[1]*100)


80/80 [==============================] - 3s 36ms/step - loss: 0.6752 - accuracy: 0.5990
59.89807844161987


In [ ]:
y_pred_v  = model.predict([X_val,new_data_v])
# print("Valid_Accuracy=>",np.mean((y_pred_v.argmax(axis=1)==Y_val.argmax(axis=1))))

y_pred_t  = model.predict([X_test,new_data_t])
# print("Test_Accuracy=>",np.mean((y_pred_t.argmax(axis=1)==Y_test.argmax(axis=1))))

y_pred  = model.predict([X_train,new_data])
# print("Train_Accuracy=>",np.mean((y_pred.argmax(axis=1)==Y_train.argmax(axis=1))))

new_data = []
for _i in range(y_pred.shape[0]):
    tmp_data = [cluster_weight[train_c[_i]],y_pred[_i,1]]
    new_data.append(tmp_data)
new_data = np.array(new_data)

new_data_t = []
for _i in range(y_pred_t.shape[0]):
    tmp_data = [cluster_weight[test_c[_i]],y_pred_t[_i,1]]
    new_data_t.append(tmp_data)
new_data_t = np.array(new_data_t)

new_data_v = []
for _i in range(y_pred_v.shape[0]):
    tmp_data = [cluster_weight[valid_c[_i]],y_pred_v[_i,1]]
    new_data_v.append(tmp_data)
new_data_v = np.array(new_data_v)


mode = 1
if mode == 0:
    new_train_data = new_data
    new_train_label = Y_train.argmax(axis=1)

    new_test_data = new_data_t
    new_test_label = Y_test.argmax(axis=1)

    print("New_Test_Accuracy=>",np.mean((y_pred_t.argmax(axis=1)==new_test_label)))

if mode == 1:
    new_train_data = new_data_t[:1500,:]
    new_train_label = Y_test.argmax(axis=1)[:1500]

    new_test_data = new_data_t[1500:,:]
    new_test_label = Y_test.argmax(axis=1)[1500:]

    print("New_Test_Accuracy=>",np.mean((y_pred_t.argmax(axis=1)[1500:]==new_test_label)))

if mode == 2:
    new_train_data = new_data_v
    new_train_label = Y_val.argmax(axis=1)

    new_test_data = new_data_t
    new_test_label = Y_test.argmax(axis=1)

    print("New_Test_Accuracy=>",np.mean((y_pred_t.argmax(axis=1)==new_test_label)))


New_Test_Accuracy=> 0.6060894386298763


In [ ]:
from sklearn.metrics import confusion_matrix,f1_score
from sklearn.ensemble import RandomForestClassifier
clf1 = RandomForestClassifier(n_estimators=10, max_depth=None,
      min_samples_split=2, random_state=0)
clf1.fit(new_train_data, new_train_label)
y_pred = clf1.predict(new_test_data)
print("RandomForestClassifier ")
print('Confusion matrix(test):\n{}'.format(confusion_matrix(new_test_label, y_pred)))
print("Test_Accuracy=>",np.mean((y_pred==new_test_label)))
print('f1-score=>(test):{}'.format(f1_score(new_test_label, y_pred)))


from sklearn.ensemble import ExtraTreesClassifier
clf2 = ExtraTreesClassifier(n_estimators=10, max_depth=None,
      min_samples_split=2, random_state=0)
clf2.fit(new_train_data, new_train_label)
y_pred = clf2.predict(new_test_data)
print("ExtraTreesClassifier")
print('Confusion matrix(test):\n{}'.format(confusion_matrix(new_test_label, y_pred)))
print("Test_Accuracy=>",np.mean((y_pred==new_test_label)))
print('f1-score=>(test):{}'.format(f1_score(new_test_label, y_pred)))



from sklearn import svm
clf3 = svm.SVC()
clf3.fit(new_train_data, new_train_label)
y_pred = clf3.predict(new_test_data)
print("SVMClassifier")
print('Confusion matrix(test):\n{}'.format(confusion_matrix(new_test_label, y_pred)))
print("Test_Accuracy=>",np.mean((y_pred==new_test_label)))
print('f1-score=>(test):{}'.format(f1_score(new_test_label, y_pred)))



from sklearn.neural_network import MLPClassifier
clf4 = MLPClassifier(random_state=1, max_iter=300).fit(new_train_data, new_train_label)
y_pred = clf4.predict(new_test_data)
print("MLPClassifier")
print('Confusion matrix(test):\n{}'.format(confusion_matrix(new_test_label, y_pred)))
print("Test_Accuracy=>",np.mean((y_pred==new_test_label)))
print('f1-score=>(test):{}'.format(f1_score(new_test_label, y_pred)))


RandomForestClassifier 
Confusion matrix(test):
[[225 271]
 [233 322]]
Test_Accuracy=> 0.5204567078972407
f1-score=>(test):0.5609756097560975
ExtraTreesClassifier
Confusion matrix(test):
[[228 268]
 [232 323]]
Test_Accuracy=> 0.5242626070409134
f1-score=>(test):0.5636998254799302
SVMClassifier
Confusion matrix(test):
[[297 199]
 [221 334]]
Test_Accuracy=> 0.6003805899143673
f1-score=>(test):0.613970588235294
MLPClassifier
Confusion matrix(test):
[[207 289]
 [149 406]]
Test_Accuracy=> 0.5832540437678402
f1-score=>(test):0.6496000000000001
